### ISSUE TITLE
Failed to save view: null is not an object (evaluating 'RNSaveView.saveToPNGBase64')

### ISSUE THREAD

**Issue by m-ruhl** [rumax/react-native-PixelsCatcher#30]
Hey 👋 ,

I wanted to use the framework.. but every test fails with this error:
`
Failed to save view: null is not an object (evaluating 'RNSaveView.saveToPNGBase64')
`

I also copied some tests from the "Demo-Project" without any success:
```js
registerSnapshot(class SnapshotClass extends Snapshot {
  static snapshotName = 'longContent';

  renderContent() {
    return (
      <View style={{ flex: 1, flexDirection: 'column' }}>
        <View style={{height: 200, backgroundColor: '#FFA07A'}} />
        <View style={{height: 300, backgroundColor: '#E9967A'}} />
        <View style={{height: 400, backgroundColor: '#FA8072'}} />
        <View style={{height: 500, backgroundColor: '#F08080'}} />
        <View style={{height: 600, backgroundColor: '#CD5C5C'}} />
      </View>
    );
  }
});


runSnapshots(appName, { baseUrl });
```

**Informations:**
  - iOS-Simualator 12.4
  - RN 60.5
  - PixelsCatcher: 0.5.1

Disclaimer:  I'm using _react-native-navigation_ which I think is a little bit hard to use with this framework... to use the screenshot testing I reverted some things so it uses the normal startup of RN.

Any idea what the problem is?

Thanks
Michael

**Comment by rumax** [comment]
Hi, sounds like an issue with linking:

>  The library depend on react-native-save-view which is used to convert View to base64 data and has native implementation. 

Is 'react-native-save-view' properly linked in your project?

**Comment by m-ruhl** [comment]
Wow, thanks for the quick reply :)

As I'm using RN60+ it should auto link, right?.. But when I run `pod install` I cannot see any mention of `react-native-save-view`

**Comment by rumax** [comment]
As a quick fix you can add it manually like this https://github.com/rumax/react-native-PixelsCatcher/blob/master/demo/ios/Podfile#L30. Please, let me know if it helps of if you find an issue why it it is not auto-linked. I'm not sure why it doesn't want to auto link, maybe because it is installed as dev dependency.

**Comment by m-ruhl** [comment]
If I explicitly add `react-native-save-view` as a dependency auto-link is working.
I think what's why for example with Lottie (https://github.com/react-native-community/lottie-react-native) you need to add both dependencies

**Comment by rumax** [comment]
According to NPM `react-native-PixelsCatcher` uses `dependencies` that are properly installed with `npm` or `yarn` command. So I do not see any issues with the dependencies definitions. Moreover it keeps root `package.json` a bit cleaner, because of less direct dependencies specified. 

But because `react-native-save-view` has native implementation and it's not a direct `dependencies` or `devDependencies` react native seems to ignore it (which also make sense and I think the reason why they put a manual linking step in the manual). I've updated readme (#33) to mention the issue and remark that `react-native-save-view` can be added to dependencies of the project.
