### ISSUE TITLE
Creating new tests results in "Image size do not match"

### ISSUE THREAD

**Issue by m-ruhl** [rumax/react-native-PixelsCatcher#31]
When I create a new Snapshot tests results in an error: "Image size do not match"

```
PIXELS_CATCHER::SERVER WARNING: File [/Users/.../snapshots/ios/refImages/TimeCell_Changeable.png] does not exists, using dummy file
PIXELS_CATCHER::SERVER: Writing file to /Users/.../snapshots/ios/uploads/TimeCell_Changeable.png
PIXELS_CATCHER::SERVER: and comparing to /Users/.../node_modules/pixels-catcher/lib/runner/server/dummy.png
PIXELS_CATCHER::APP::SNAPSHOTS_CONTAINER: --SaveView.save, size is 86620
PIXELS_CATCHER::SERVER: File created
/Users/.../node_modules/pixelmatch/index.js:19
        throw new Error('Image sizes do not match.');
```

I get the reason, because it compares it to the dummy image. If I move the uploaded image to the reference folder.. in the next run it has no problems.

In my case I created a couple of tests at once.. So in this case I need to run it multiple times to run through every new test

**Comment by rumax** [comment]
> because it compares it to the dummy image

It was done on purpose. Another option I see is to pass the test and create a reference image automatically, but this will lead to issues with CI, when, for example, reference image is not added to the project. And another reason was that at first run, you check manually if uploaded image corresponds to what is expected and after it can be moved to the reference images.

> So in this case I need to run it multiple times 

I would say no need in second run, because tests will pass, and if it is integrated to CI, you'll get the second check from CI.
Or you can run only required tests by commenting other tests and reloading the app.

Btw, what would be your implementation for initial tests?

**Comment by m-ruhl** [comment]
Sorry, I should have made it clearer...

If I run the `pixels-catcher` with new test cases. With the first new test case, the error above occurs. With that error, the runner stops.. The following test cases are triggered in the app, but cannot upload the screenshots because the runner has been stopped.

So in that case, I can only move the screenshot of the first new test cases from uploaded to refImages, because the other ones are not there. So I need to run it multiple times to have all refImages

**Comment by rumax** [comment]
@m-ruhl version `0.5.2` with the fix is published
