### ISSUE TITLE
Make comparison threshold configurable

### ISSUE THREAD

**Issue by sam-barker** [rumax/react-native-PixelsCatcher#53]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to say "when the images are compared, It's okay if 90% of the pixels are the same" or "when the images are compared, it's okay if 70% of the pixels are the same".

The problem with always having this number hard-coded and non-configurable is it makes tests more flakey

**Describe the solution you'd like**
To be able to configure as a CLI argument, or in the json file config some sort of parameter like "comparisonThreshold" to be able to allow some pixels to be different

**Describe alternatives you've considered**
Apart from forking and doing this, nothing else.

**Additional context**

**Comment by rumax** [comment]
Hi @sam-barker 

> The problem with always having this number hard-coded and non-configurable is it makes tests more flakey

Can you, please, provide a real example where tests are results are flaky? If it is a bug in pixels-catcher and if I know how to reproduce it, I would prefer to fix it, instead of making a workaround. The PixelsCatcher works in different projects and I never had flaky results.

> It's okay if 90% of the pixels

Assuming you have a page where you need to render some form and one of the expected values is changed from `0` (zero) to `-` (dash). What would be a percentage in this case? Or let's say the line wrap didn't work and part os some word was out of the screen?

<img width="290" alt="Screenshot 2020-05-25 at 20 49 33" src="https://user-images.githubusercontent.com/2707180/82837458-621e7600-9ec9-11ea-8c56-35b10e9240f7.png">

what is the percentage in this case?

> it's okay if 70% of the pixels are the same

I doubt if UI tests are necessary in this case. Maybe the [Pixels matter or easy UI screenshot testing in React Native](https://medium.com/ing-blog/pixels-matter-or-easy-ui-screenshot-testing-in-react-native-6e41ba91b225) article can help. There are also some useful links inside.


<hr>

Or this test case result:

![WebViewTest](https://user-images.githubusercontent.com/2707180/82982262-15808b00-9fee-11ea-93f3-dbf9bec1fc5d.png)

> 'Files mismatch with 87 pixels'

That is 0,0031%

How would you estimate if it passed or not?
